title: 'ISC(2) El Paso Chapter'
description: 'We are an ISC(2) chaptering organization with goals of growing the number of ISC(2) certification memberships across the El Paso-Midland-Alpine area in West Texas.'
include:
  - _assets
  - _navigation
header_pages:
- _navigation/events.md
- _navigation/blog.md
- _navigation/about.md
- _navigation/contact.md
theme: minima
minima:
  social_links:
    linkedin: isc2elpaso
    twitter: isc2elpaso
