title: 'ISC(2) El Paso Chapter'
description: 'An ISC2 chaptering organization with goals of growing the ISC2 certification memberships in the West Texas area of El Paso-Midland-Alpine area.'
include:
  - _assets
  - _navigation
header_pages:
- _navigation/events.md
- _navigation/blog.md
- _navigation/about.md
- _navigation/contact.md
theme: minima
minima:
  social_links:
    linkedin: isc2elpaso
    twitter: isc2elpaso
