title: '(ISC)2 El Paso Chapter'
author: 'Victor Fernandez III'
description: 'We are an (ISC)2 chaptering organization with goals of growing the number of (ISC)2 certification memberships in the El Paso-Midland-Alpine area of West Texas.'
include:
  - _assets
  - _navigation
header_pages:
  - _navigation/events.md
  - _navigation/blog.md
  - _navigation/contact.md
  - _navigation/contact2.md
  - _navigation/about.md
theme: minima
permalink: /:title:output_ext
minima:
  social_links:
    linkedin: isc2elpaso
    twitter: isc2elpaso
